{{- if .Values.helm_hpa_bfe3cdcb7dad5550a5b8bbe3048b1b45.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.helm_hpa_bfe3cdcb7dad5550a5b8bbe3048b1b45.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.helm_hpa_bfe3cdcb7dad5550a5b8bbe3048b1b45.workload_kind }}
    name: {{ .Values.helm_hpa_bfe3cdcb7dad5550a5b8bbe3048b1b45.workload_name }}
  minReplicas: {{ .Values.helm_hpa_bfe3cdcb7dad5550a5b8bbe3048b1b45.min_replicas }}
  maxReplicas: {{ .Values.helm_hpa_bfe3cdcb7dad5550a5b8bbe3048b1b45.max_replicas }}
  metrics:
    {{- if .Values.helm_hpa_bfe3cdcb7dad5550a5b8bbe3048b1b45.target_cpu_utilization_percentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_bfe3cdcb7dad5550a5b8bbe3048b1b45.target_cpu_utilization_percentage }}
    {{- end }}
    {{- if .Values.helm_hpa_bfe3cdcb7dad5550a5b8bbe3048b1b45.target_memory_utilization_percentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_bfe3cdcb7dad5550a5b8bbe3048b1b45.target_memory_utilization_percentage }}
    {{- end }}
{{- end }}