apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.helm_service_account_af69fe6c90ef537783ae99717891c83b.name  }}
  labels:
  {{- range $key, $value := .Values.helm_service_account_af69fe6c90ef537783ae99717891c83b.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.helm_service_account_af69fe6c90ef537783ae99717891c83b.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
automountServiceAccountToken: {{ .Values.helm_service_account_af69fe6c90ef537783ae99717891c83b.automount }}
