helm_hpa_bfe3cdcb7dad5550a5b8bbe3048b1b45:
    enabled: true
    max_replicas: 2
    min_replicas: 1
    name: workspace
    target_cpu_utilization_percentage: 50
    target_memory_utilization_percentage: 50
    workload_kind: Deployment
    workload_name: workspace
helm_ingress_6daa1655456f5d7a819f63eaf5b53df2:
    annotations:
        kubernetes.io/ingress.allow-http: "false"
    class_name: workspace
    default_backend_name: workspace
    default_backend_port: 80
    labels:
        service: myapp
    name: workspace
    rules: []
    tls: ""
helm_service_a3067c6442e856f895aa9173c4e64266:
    name: workspace
    port: 80
    protocol: TCP
    selector_labels:
        service: myapp
    target_port: 80
    type: ClusterIP
helm_service_account_af69fe6c90ef537783ae99717891c83b:
    annotations: {}
    automount: false
    labels: {}
    name: workspace
helm_workload_35df4b4a28a45fb78705226eed238678:
    env:
        ENVBUILDMODE: ""
        FLASK_ENV: ""
    env_from_config: []
    env_from_secret: []
    image: ""
    image_pull_policy: Always
    image_pull_secret: null
    image_tag: ""
    kind: Deployment
    labels:
        service: myapp
    name: workspace
    port: 80
    protocol: TCP
    replicas: 1
    service_account: workspace
    volume_mounts: []
    volumes: []
